### ISSUE TITLE
Is is possible to use subscriptions with SSR?

### ISSUE THREAD

**Issue by loelsonk** [reactql/kit#10]
I could not really find an answer and I am not sure if it is good place to ask.

```
yarn -v 0.22.0
npm -v 4.1.2
node -v 7.5.0
reactql version 2.1.0
```

Is is possible to use subscriptions with SSR? I am aware that nodejs does not have direct support for websockets, so we have  to install package/library to add desired functionality...

[SubscriptionClient](https://github.com/apollographql/subscriptions-transport-ws
) is used for client/browser.

Of course I use Graph.cool as my backend service.

`webSocketImpl: Object - optional, WebSocket implementation. use this when your environment does not have a built-in native WebSocket (for example, with NodeJS client)`

 
Here is part of my apollo.js file:

```
import WebSocket from 'ws';
import {SubscriptionClient, addGraphQLSubscriptions} from 'subscriptions-transport-ws';

const wsClient = new SubscriptionClient(APOLLO.socketsUri, {
  reconnect: true,
  connectionParams: {
  }
}, WebSocket); // webSocketImpl object

```

Error I am getting when I don't use `webSocketImpl object`
![Image](https://i.imgur.com/vzWR4sF.png)

It does not seem to work when I use npm run build-run ([console dump](https://pastebin.com/7tES7vU2)). Clearly I am doing something wrong, can I get guidance or can you point me to an example which shows how to implement subscriptions with SSR?

**Comment by jtmthf** [comment]
@loelsonk You actually don't want to enable the `SubscriptionClient` on the server. As the subscription is for reacting to a stream of real time of events, it's unneeded in the SSR phase. During SSR you just need to get the current state of the data you need. Then once your app mounts on the client-side, you can subscribe to changes.

Check out the client entry point from `githunt-react`, the semi-official example from the Apollo devs. https://github.com/apollographql/GitHunt-React/blob/master/ui/client.js#L24. Note how the subscription client is only added on the client entry and not the server.

**Comment by leebenson** [comment]
I plan on writing a guide that demonstrates subscriptions in practice in a universal way. Like @jtmthf said, this would be done by fetching only the initial data on the server, piping it down to the client, and then letting the _client_ subscribe directly.

I'll close this for now, and will drop a note back when the docs have been updated with the guide.

**Comment by loelsonk** [comment]
@leebenson  I will definitely check your guide, just let me know.
@jtmthf @leebenson Thanks for help I've got it to work, just tested it and my subscription works in production and in development mode.

So here are my small changes to `apollo.js` file. Changes are small but it is working as intended. What do you think? Are there any "gotchas" with this code or this is proper way of implementing subscriptions?

```js
// Silly naming createNewNetworkInterface, networkInterface, createNetworkInterface
function createNewNetworkInterface() {
  const networkInterface = createNetworkInterface({
    uri: APOLLO.uri
  });

  // Auth0 token
  networkInterface.use([{
    applyMiddleware (req, next) {

      if (!req.options.headers) {
        req.options.headers = {};
      }

      if (!SERVER) {
        req.options.headers.authorization = `Bearer ${localStorage.getItem('id_token')}`;
      }

      next();
    },
  }]);

  if (SERVER) {
    return networkInterface;
  }

  // Client side only
  const wsClient = new SubscriptionClient(APOLLO.subscriptionUri, {
    reconnect: true
  });

  return addGraphQLSubscriptions(
    networkInterface,
    wsClient,
  );
}

function createClient(opt = {}) {
  return new ApolloClient(Object.assign({
    reduxRootSelector: state => state.apollo,
    networkInterface: createNewNetworkInterface()
  }, opt));
}
```

There is another thing I would like to ask, how to handle authentication with SSR? I am using Auth0 + GraphCool. For client side of course there is localStorage, but for server side with koa? I tried [koa-generic-session](https://github.com/koajs/generic-session) to store my `auth0_token`, it actually works. But is this proper way to do it?

Should I create new issue for this(not really an issue but just a question)?

**Comment by leebenson** [comment]
One way to handle authentication is to pass the auth token back to the client as a cookie.

This way, you're using the initial SSR as a 'proxy' for authentication - on the very first call from the server, any Bearer token received from the API server would be returned as a cookie (down to the browser), allowing future requests to the server to reuse that same token.

On the client, you could then store the request in `localStorage`, making it available to future direct requests to the GraphQL endpoint via a custom `Authorization:` header, like you've done in your example.

There are a few gotchas in this scenario to be aware of:

1. **You will need to use cookies _and_ `localStorage`.** You can't use localStorage on its own, because any future requests back to the server handling SSR need to pass the auth token in the HTTP header of the request (localStorage is obviously only available after the request has already returned.) And you probably can't use cookies on their own, because...

2. **Cookie security needs to be considered**. Allowing programmatic access to cookies is generally a bad thing- it opens the door to rogue scripts that could potentially read the token, and pass it off-site via an AJAX request. If it's a cookie that does no kind of origin checking, then that could potentially give full access to the API to an attacker. Disallowing cookie reads means passing it downstream via some other means _along with_ the cookie, so that you have Javascript access to it later (this could be a good use of your Redux store!)

3. **Original headers might be a factor**.  Per no. 2 above, if an auth token, say, hashes the `User-Agent` and some other identifying information, or returns a secondary cookie that is required along with auth, you may need to factor those considerations on the SSR render by copying over the original headers to effectively 'proxy' any server requests. This won't help if the API server is using your IP as part of its auth model, but if you're designing the GraphQL endpoint yourself, you might want to implement secondary vectors into your auth routine such as HTTP headers, as a sanity check against the origin.

There's probably no way to standardise this, because the implementation details are up to the GraphQL server. Some use HTTP headers to communicate bearer tokens; others might send a token back as part of the query data.

I think it makes sense to write an auth guide, though, that tackles some of these common scenarios and possibly make the default behaviour of the Apollo client on the server to mimic the headers it receives from the client to act more like a proxy.

I'll open a separate issue in [reactql/docs](https://github.com/reactql/docs) as a reminder.
