### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by nwicakson** [reactql/kit#126]
I want to check if i can deploy my work.
https://github.com/nwicakson/informatics-reactql

The localhost:8080 looks okay. But when i run npm run build-run and then visit localhost:4000 at my computer, I got error message "window is not defined".
Can I check it like that? *first time to deploy

I have updated reactql from 2.8.5 to 2.10.0, but still got this error.
Am I doing something wrong in my code /src?

**Comment by gihrig** [comment]
`run npm run build-run` and then visit `localhost:4000`

@nwicakson that is correct, works fine for me
ReactQL 4.10.0 (fresh install)
Mac OS 10.11.6

I was unable to run your project without starter data. If you would like to upload a minimal data set for testing, I will take it for a spin to see if I can spot anything.

Otherwise, I would suggest rolling back to earlier commits to see if you can spot where the problem started.

**Comment by webexpert5** [comment]
Reactql provides both browser side and server side rendering. 

localhost:8080 is Browser rendered. That means all the files are loaded first and then rendered. By that time window variable is available, because you are in browser.

But when you build and run, the app is server rendered on the initial load and later the browser kick in.
So during the initial load, the window variable is not available and you see that error.

You can test on localhost:8081 for more info.

**Comment by nwicakson** [comment]
@gihrig Thank you, it turns out the explanation from @webexpert5 was right.
It's because:
- I didn't check if this is SERVER or not
before `const shareUrl = window.location.pathname;`
after `const shareUrl = !SERVER ? window.location.pathname : null;`
and
I called window at react-helmet
before `<meta property="og:url" content={window.location.pathname} />`

**Comment by Floridus** [comment]
Hello,

I have the same problem and have already looked at localhost: 8081. However, nowhere is an info about the error displayed here. So I do not know at all where this mistake is.

In my own code I do not use the window variable but only localStorage. Through the project search, I found only the files "lib/redux.js" and "ssr.js" where the variable window is used. Otherwise many times in the vendor.js file. I think it will probably have something to do with the vendor.js file. What can I do to solve this?
