### ISSUE TITLE
CSS imports from node_modules

### ISSUE THREAD

**Issue by jtmthf** [reactql/kit#13]
One thing I cannot do so far is importing css from third party sources, without having it processed through css-modules. As third party css generally doesn't follow the `*.global.css` rule, it gets processed through css-modules and gets its class names messed up. I've tried a couple of approaches using different include and exclude rules, but haven't found a solution that works yet.

**Comment by leebenson** [comment]
@jtmthf - have you tried creating a `styles.global.css` and using `@import 'path/to/external.css'` in there? That should work. e.g.:

**app.js**
```js
import React from 'react';
import './style.global.css';
export default () => (
  <h1>Check the CSS in source</h1>
);
```

**styles.global.css**
```css
/* note this is request a 'normal' .css -- not a global one */
@import './external.css';
```

**external.css**
```css
.test {
  color: red;
}

.test2 {
  color: white
}

.another {
  color: blue;
}
```

... retains the original classnames in production:

<img width="623" alt="screen shot 2017-04-23 at 22 23 10" src="https://cloud.githubusercontent.com/assets/719722/25317601/7a818acc-2873-11e7-9b1a-623a609f5d45.png">

Does that help your use case?

**Comment by jtmthf** [comment]
@leebenson Thanks! That works there. I was trying imports from both js files and also within the `:global` selector in modularized css files. Seems like importing from from global css preserves the global configuration.

**Comment by leebenson** [comment]
Excellent, glad to it worked @jtmthf.

Yep, as long as the _final_ file you're importing from is named in the `.global.css` format, everything that happens within that file should remain 'global'.

Using `:global { @import './somethingElse.css' } ` within a plain .css file technically _ought_ to work, but it seems that the current importer processes that as a regular require statement that is also run through css-modules, rather than just appending it to the current output for the _final_ batch to take care of. 

There's a new plug-in I recently contributed to called (postcss-nested-import)[https://github.com/eriklharper/postcss-nested-import] that attempts to do just that. I fixed a few bugs yesterday and haven't given it a thorough enough tyre-kicking to use in ReactQL yet, but this might solve the edge case you ran into by side-stepping css-modules on imported files.

Also, if you were using SASS throughout the whole chain, this works fine too because `@import` uses `node-sass` when it encounters a `.scss/.sass` file and does similar to the plugin above, by seemingly pre-compiling and then concatenating the chain before it hits css-modules:

**test.scss**
```scss
// this works fine -- and throws back the original classnames, as expected
:global {
  @import './external.scss';
}
```

But, calling a regular `.css` file in the above example defers back to css-modules.

I'll leave this open until I can confirm postcss-nested-import or similar fixes it.
