### ISSUE TITLE
Testing with Jest does not work (es6 modules not transpiling for node)

### ISSUE THREAD

**Issue by biels** [reactql/kit#133]
Running npm test with some .test.js fiels under /src does not work out of the box. 
Well, in fact it does until you try to import a file using es6 modules. It complains about "SyntaxError: Unexpected token import". I think babel-jest has to be configured properly. 
Tested it under node v9.3.0.

As additional information that might or might not be useful: Maybe it is not finding the provided configuration files (jest.config.js and jest.transform.js) for some reason, or it is ignoring them because of some webpack configuration?

**Comment by biels** [comment]
I discovered that if tou comment out the contents of the jest.config.js it works (at least under node 9.3.0). However, then monkeypatched functions like .merge() which is used at reducers, are not avaliable when testing. This needs a fix as soon as possible, because this means there is currently no way to test reactql reducers!

**Comment by dougajmcdonald** [comment]
@biels I'm interesting the answer to this too, posted the same problem in the cli here: https://github.com/reactql/cli/issues/96

**Comment by dougajmcdonald** [comment]
I found the problem, it's a simple one, the regex is wrong!

the `(x)` isn't an optional x which I presume is what it's meant to be.

in your `jest.config.js` change the `transform` bit from:

```
  transform: {
    '^.+\\.js(x)$': '<rootDir>/jest.transform.js',
  },
```

to

```
  transform: {
    '^.+\\.jsx?$': '<rootDir>/jest.transform.js',
  },
```

The `?` matches 0-1 preceding characters so is the right one to use here.

**Comment by dougajmcdonald** [comment]
As a side note, if you wanted to enable coverage the `collectCoverageFrom` array in `jest.config.js` takes a glob, so to match `.js` and `.jsx` you'd need the following:

```
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
  ],
```

**Comment by dougajmcdonald** [comment]
Lol, just noticed there is already a PR for this: https://github.com/reactql/kit/pull/112

I submitted another, literally the same! hope this gets merged soon! *ehem* @leebenson ;-)

**Comment by leebenson** [comment]
I appreciate your activity today on the ReactQL issue board, @dougajmcdonald.

FYI, I'm currently working on a major new ReactQL release that will bring about some significant changes to how the projects are laid out. See [here](https://github.com/reactql/kit/issues/80#issuecomment-353722198) for more info.

Since the next release will fundamentally change the way ReactQL works (hint: everything is just an NPM package, rather than a full starter kit), I'm holding off from accepting PRs since they'll quickly become redundant.

Things like unit testing will be left as an exercise to the user. ReactQL will no longer be quite so 'opinionated' about those things.

Watch [this thread](https://github.com/reactql/kit/issues/80#issuecomment-353722198) for release details as it happens.

**Comment by dougajmcdonald** [comment]
Hi Lee, NPS and thanks for the info. This really does help as I only found the reactql project last week and my plan is to migrate and existing react / redux / saga project I have. The aim is that I want to make use of graphql on the backend so was testing CI, docker, testing and code coverage to see if it suits.
Sounds like I should hold fire a week, so you've saved me s bunch of effort! Ta! Will be watching eagerly.
