### ISSUE TITLE
Only create store on initial HTML document request (SSR)

### ISSUE THREAD

**Issue by NotJustClarkKent** [reactql/kit#137]
Hi, is anyone aware of a way to only create a store once on the server so expensive operations like getting the initial state from an async source only fire for the initial request (HTML document)? I've tried using Koa middleware hooks provided in `config.js` and [`ctx.is('html')`](https://github.com/koajs/koa/blob/master/docs/api/request.md#requestistypes) to no avail.

Right now I notice a state request to my API server for every call including static assets. Here is a screenshot of a single request to `http://localhost:8081/` console logging above [server.js:312](https://github.com/reactql/kit/blob/master/kit/entry/server.js#L312) shows 5 unnecessary store creates (in my case 6, ignore /cookie) for every page load:
![screen shot 2017-12-27 at 15 46 55](https://user-images.githubusercontent.com/2006387/34393103-1e001610-eb1e-11e7-9b90-6eff02891e2c.png)

Perhaps this is more of a Koa question or maybe there is a technique to handle this that I'm unaware of but after searching for an answer I've come up empty handed. Any help/guidances would be appreciated!

**Comment by leebenson** [comment]
The issue is that [staticMiddleware()](https://github.com/reactql/kit/blob/master/kit/entry/server.js#L131-L149) is being attached _after_ regular middleware, so whatever you have in your previous middleware functions will always run first.

There are pros and cons to this. The pros are that you get lower-level control of _every_ request - even that which is ultimately served statically. So if you want to do, say, user authorisation to detect whether a file is 'allowed' to be sent down the pipe, you can.

The cons are that you are orchestrating a full stack of middleware _before_ you get to do the basic function of sending a file down the line. This means a new store object, and a new Apollo client, which is going to add a millisecond or two to the response time, and involves instantiating some memory.

In practice, this is usually not that big of a deal; it literally is just a millisecond or two for most use cases, and the memory is marked for garbage collection as quickly as it takes to respond to the request, so there's limited impact.

This can be improved in [kit 3.0](https://github.com/reactql/kit/issues/80#issuecomment-353722198) by shifting the middleware around slightly, so that `beforeMiddleware()` and `afterMiddleware()` come before and after the static implementation, respectively, so you have slightly finer control.

**Comment by NotJustClarkKent** [comment]
Makes sense, thank you. I will have a look at 3.0 but will deal with the extra calls for now in 2.0.
As usual, thanks for the prompt reply Lee!
