### ISSUE TITLE
Thoughts on allowing the option to opt out of ssr?

### ISSUE THREAD

**Issue by babsonmatt** [reactql/kit#22]

**Comment by jtmthf** [comment]
@babsonmatt I was planning on doing a PR for this sometime this week. I was going to have separate options to opt out of either or both SSR and apollo server side fetch. My idea was the the Koa server would still have to run, but those options could be opted out of. What this doesn't address is being able to serve the application without a node server such as on github pages or using only nginx. Doing that would require bring webpack's html plugin to write the proper hashed assets to `index.html` at build time.

**Comment by leebenson** [comment]
I'm sure you're already aware of this, but just in case it isn't clear to anyone reading - it's possible to opt out of GraphQL data fetching on the server on a per-component basis.

[This link](https://reactql.org/docs/graphql#How-can-I-prevent-data-loading-on-the-server) in the docs shows how.

It's not truly client-side only since a Koa server is still involved in serving the initial page and bundle, but it prevents the server awaiting async data loading.

A PR for building a client-only bundle along with a sample HTML page would be ideal. I imagine that could be run via `npm run build-client-only` or something like that, and would be the same dump of browser and vendor files, alongside a sample `index.html` that knows how to request them.

Then, hosting on git pages or anywhere else would just be a case of copying over the `dist/public` static files.

**Comment by leebenson** [comment]
Just an FYI that I'm working on this issue today

**Comment by leebenson** [comment]
Released in [1.2.0](https://github.com/reactql/kit/releases/tag/1.2.0)

Now you can run:

`npm run build-browser-only`

... and it'll generate an `index.html` alongside the regular browser bundles, to correctly load the latest hashed CSS/JS.

You can then simply upload `dist/public/*` to a static host, et voila - working client-only site!

**Comment by babsonmatt** [comment]
@leebenson Any plans to do something like npm run start-browser-only?

**Comment by leebenson** [comment]
@babsonmatt - I'll add that to the next version.

**Comment by leebenson** [comment]
Just a heads up that [1.3.0](https://github.com/reactql/kit/releases/tag/1.3.0) adds a static server, and changes the NPM run commands slightly to fit:

Now you have:

`npm run build-static` <-- build a static bundle
`npm run static` <-- run a previously built static bundle on port 5000
`npm run build-static-run` <-- do both
