### ISSUE TITLE
[Q] Best approach to authentication.

### ISSUE THREAD

**Issue by pfulop** [reactql/kit#38]
Hi,
First I'd like to thank you for such an amazing work.

I have question about authentication. When we used custom boilerplate, we tend to put JSON Web Token in store, and access the store from apollo network middleware.

```javascript
import {
    store
} from './index'; //I can import it here since this will run only on client
const networkInterface = createNetworkInterface({ uri: '/graphql' });
networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {}; 
    }
    req.options.headers['authorization'] = store.getState().token.token;
    next();
  }
}]);
```

In your boilerplate, you use same code for both server and client initialization (with minor option changes). This basically makes it hard to access store from client (since it would call client side store initialization during ssr and all that stuff). Do you have some kind of recommended approach to solve authorization?

```javascript
const networkInterface = createNetworkInterface({
  uri: APOLLO.uri,
});
networkInterface.use([
  {
    applyMiddleware(req, next) {
      if (!req.options.headers) {
        req.options.headers = {}; 
      }
      const store = require('../entry/browser.js').store; //workaround to require store only on client
      req.options.headers.authorization = store.getState().auth.token;
      next();
    },
  },
]);
```

**Comment by leebenson** [comment]
@pfulop - I'll be tackling authentication patterns in an upcoming version. It's actually something I'm doing in a live project now, so the kit will get some 'official' support for it.

The way it'll be handled is likely a combination of cookies and localStorage. There are stub functions [here](https://github.com/reactql/kit/blob/master/kit/lib/apollo.js#L28-L38) that allow customisation of the client based on each environment; the server will read the auth token as a cookie and pass that on to third-party requests, while the client version will use localStorage to avoid security issues of reading cookies from JS.

Will have some code ready over the coming days.

**Comment by pfulop** [comment]
Sounds good, can't wait.

**Comment by mwarger** [comment]
👍

**Comment by gihrig** [comment]
@leebenson 

>the client version will use localStorage to avoid security issues of reading cookies from JS.

My understanding is that local storage is vulnerable to being read from JS, but (secure) cookies are not. Perhaps I misunderstood your intent, but for anyone interested, there's an article from Stormpath on the subject here: [Where to store your jwts - cookies vs html5 web storage](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage). tldr; jump to the Conclusion section.

**Comment by leebenson** [comment]
Yes @gihrig, that's exactly right.

Depending on how how your authentication system is implemented, it _might_ be necessary to utilise both cookies and localStorage (or some kind of ephemeral approach to allowing access in JS).

The reason is this:

When a user hits the ReactQL web server, the web server will query the GraphQL server for data. It may send down a JWT at that point and consider that the session is 'established'. Rather than the user's browser then making a second request and establishing a new session, the first and original session can be 're-used'.

The ReactQL web server can pass the JWT down with the initial session data, no problem - but it's generally a more secure strategy to send it down as a HTTP header so that the JWT doesn't get exposed along with the initial HTML dump.

At that point, there's a cookie relationship between the user's browser and the ReactQL web server.

BUT, there's a problem here - that cookie will only work between browser -> web server. If the GraphQL server is stored off-site and interprets sessions via cookie or via a JWT token, we need some way of getting that info to the server to authenticate the existing session. We can't use the original cookie, because that's not accessible in Javascript, and the URL is (potentially) not the same to automatically pass along the cookie header with the HTTP request.

We need a strategy that will work with THREE parties:

1. The user's browser
2. The ReactQL web server (i.e. the project's main domain, for SSR)
3. The GraphQL server

To achieve this, we could do something like this:

1. User goes to www.example.com, which is running a ReactQL web server
2. ReactQL web server fires GraphQL queries against a third-party GraphQL server
3. GraphQL server sends back a JWT token
4. ReactQL web server stores the JWT in the response, as well as sets the JWT as a cookie
5. The user's browser takes the JWT and stores it in `localStorage`. The Apollo instantiation code is modified to automatically pass the JWT to the GraphQL server along with every future request.
6. The next time the user goes to www.example.com, the secure cookie is passed along to the ReactQL web server, which re-uses that same JWT in its communication with the GraphQL server - essentially acting as a proxy and ensuring the SSR matches the user's authenticated session.

Obviously, there are downsides to this:

1. You're exposing the JWT token on the initial render. If the connection is over SSL, this shouldn't generally be a problem, but it's still part of the response body and possibly subject to caching.

2. You have a JWT in two places- stored as a cookie, and in `localStorage`. That's two possible attack vectors for hijacking a session.

----

In any case, use of JWT should be coupled with a server-side strategy to ensure that sessions can be invalidated by the server prior to expiration. This would typically be a 'sessions' table in a DB that is pinged before the request us processed to check validity.

There are parts of the overall authentication approach that are somewhat outside of the scope of the ReactQL starter kit. At the same time, I'd want to make sure whatever support is offered is 'best practice' and doesn't inadvertently push users to making poor implementation decisions that weaken security.

I need to think about this some more to strike the balance of general purpose use with some good patterns that enforce good habits.

I may wind up implementing a sample GraphQL server inside of ReactQL (similar to what's already offered in the [examples repo](https://github.com/reactql/examples/tree/master/graphql-server)) which has some dummy GraphQL auth and JWT handling.

Need to think about it a bit more.

**Comment by gihrig** [comment]
@leebenson 

> I need to think about this some more to strike the balance of general purpose use with some good patterns that enforce good habits.

Sounds fantastic! Thanks for the detailed expose'. I'm really looking forward to trying out your implementation ✨

**Comment by tzarger** [comment]
@leebenson Interested in seeing your implementation as well. One thing to keep in mind, is that it would be nice if you can add another strategy which is when you have a mobile app as well that would need to talk to the GraphQL server. Say you have an included [GraphQL Server](https://github.com/reactql/examples/tree/master/graphql-server) and the web side is SSR and you also have a mobile app that needs integration as well. You could not use Cookies in the mobile app and would need to send the JWT token to the mobile app on login, so the mobile application could then pass back the token to the GraphQL server on every request using most likely an Authorization header.

**Comment by leebenson** [comment]
@tzarger - that's basically the strategy I had in mind. JWT would be the primary mechanism for communicating with the GraphQL server - the initial cookie to the web server for SSR is just a means to render the initial HTML, since on the first request we're limited to HTTP headers.

This is high on my to-do list, so I'll get round to this real soon.

**Comment by TimMikeladze** [comment]
@leebenson Just heads up in case ReactQL is interested in consuming these packages in the future: we're working on full stack authentication over at https://github.com/js-accounts/ and there are React and GraphQL packages already. We do not however have a Koa middleware yet, last I checked ReactQL uses a Koa server. In the future it may be possible to avoid writing server specific middleware entirely and just require the developer to either include the accounts resolvers or start up a separate `/accounts` graphql endpoint.

At the moment we're in the process of a refactor of all the packages to Typescript as well as changing the core API to support strategies other than password login and optional cookie support in favor of JWTs. Plus additional documentation for all the packages.

**Comment by tsdexter** [comment]
@leebenson if you want to avoid adding a GraphQL server to the kit I have access to the graphcool Schema Extensions Beta which allows you to roll your own resolvers and other server side code - I can create a project and add you as a user if you want use that for the setup. 

https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405

https://github.com/graphcool-examples/functions/tree/master/authentication/email-user-management

**Comment by leebenson** [comment]
FYI for related threads - see https://github.com/reactql/kit/issues/59#issuecomment-323509731 for an update on adding auth.

**Comment by leebenson** [comment]
Thanks @tsdexter, but I've decided to avoid using Graph.cool in starter kit code, to provide a more complete example of end-to-end GraphQL (client + server) without reliance on any third-party service.

A local GraphQL server was added in [2.0](https://github.com/reactql/kit/releases/tag/2.0.0) by default, and subsequent releases have enabled better orchestration of GraphQL config. So it's up to you in each ReactQL project whether you wish to have an internal server, or point externally.

If you're opting for a local server, in your `src/app.js` you'd simply do:

```
// This enables the built-in GraphQL server isomorphically, and tells the client
// to use an Apollo URI that points to the server
config.enableGraphQLServer();

if (SERVER) {
  // We load the GraphQL schema only on the server, to avoid inflating the client bundle size
  config.setGraphQLSchema(require('src/graphql').default);
}
```

If you want to point externally, you just do:

```
config.setGraphQLEndpoint('http://example.com/some/graphql/server');
```

By default in both cases, `/graphql` will show a [GraphiQL](https://github.com/graphql/graphiql) browser for running queries. This can be disabled by passing `false` to the above two functions (see [the `config.js` source](https://github.com/reactql/kit/blob/master/kit/config.js) for the correct function signatures), or by explicitly setting an alternative endpoint passed as a string.

As mentioned above in https://github.com/reactql/kit/issues/59#issuecomment-323509731, I've been working on an internal auth implementation this week based on Sequelize and an in-memory SQLite DB, to offer a realistic scenario where `users` and `sessions` tables are stored in a DB, and we're making email/password attempts against it.

The app will also demonstrate periphery patterns for things like password hashing via bcrypt, mapping Sequelize DB table types to GraphQL, handling JWT/cookies on subsequent requests and SSR, and using custom middleware and routes to allow for Passport.js integration (or similar.) -- all of which will show up in any production app. This has all been heavily commented, of course, to talk through how it's wired up.

I'm hoping to get the first version up in the [examples repo](https://github.com/reactql/examples) repo by the end of the weekend (possibly early next week, if time gets away.)

Note all of the lower-level plumbing to make this happen will be in the kit, but all of the code - DB, GraphQL types, Redux reducers, custom routes, JWT handling, etc - will all happen in userland at `src/app.js` to allow for the infinite number of different ways you might choose to implement this, so this will be an example repo and not something that comes out-the-box with a new starter kit.

**Comment by leebenson** [comment]
Quick update:

After some delays this week, I've now finished the first version of authentication and will be releasing to the examples repo tonight. Will post here when done.

This first version introduces 'universal' JWT (available on `localStorage` in the client, and via cookies to subsequent SSR requests) to enable session re-loading in any environment.

Here's a sneak peak at what it looks like:

<img width="799" alt="screen shot 2017-08-26 at 09 23 02" src="https://user-images.githubusercontent.com/719722/29739850-320fa1fa-8a40-11e7-9fd9-f7981cf728d2.png">

Can't wait to show you -- look out for the update tonight 😄

**Comment by leebenson** [comment]
It's ready! -> https://github.com/reactql/examples/tree/master/auth

Will follow-up soon with a video explainer - there's a lot going on here.

**Comment by leebenson** [comment]
Video explainer on YT -> https://youtu.be/s1p4R4rzWUs

I'll go ahead and close this now, but will update the thread once I've also added social logins.

**Comment by leebenson** [comment]
Passport.js has been integrated, with a Facebook example ->

https://github.com/reactql/examples/tree/master/auth

Video commentary to follow later.

**Comment by utkuturunc** [comment]
@leebenson Why not use cookies both in client and server?

We can set httpOnly to true so that JS cannot read cookies.

POST /login (or POST /auth) can set the cookie.
POST /logout (or DELETE /auth) can remove the cookie.
GET /auth can get the users current status (and may return user profile information)

This way the client doesn't need to access the cookie anytime and we have a more secure and simpler solution for authentication.

**Comment by leebenson** [comment]
@utkuturunc - the example I posted demonstrates both JWTs and cookies, because often the front-end has no control over how the back-end is implemented , and many GraphQL servers won't implement cookies directly. In our example, we only use cookies for the initial SSR -- everything else is a JWT token.

Of course, in your own app, you can implement it however you want. This isn't an 'official' implementation - it's just one example of how you _might_ choose to do it yourself.

**Comment by ofairfoul** [comment]
@leebenson thanks for your example and video that is really helpful. One thing I don't fully grasp is that you mentioned it should work x-domain. But if the graphql server is on a different domain to the ssr server, after calling the login mutation how can the graphql server set the cookie to be used on the subsequent requests to the ssr server?

**Comment by clodal** [comment]
Updated link to auth example mentioned is now here: https://github.com/reactql/example-auth
