### ISSUE TITLE
Flow types enhancement

### ISSUE THREAD

**Issue by KROT47** [reactql/kit#39]
Greetings!

First of all, Great work! Thanks!)

What do you think of adding [Flow](https://flow.org/) to the kit?

**Comment by leebenson** [comment]
I don't use Flow personally (yet), but I'm open to supporting it as long as it doesn't get in the way (which I believe is one of the USPs of Flow, right?)

**Comment by KROT47** [comment]
Hello again)

I've added flow support to kit. Look at it [here](https://github.com/KROT47/kit/tree/flow) and tell your thoughts. I can create PR if all is ok. Or maybe you think smth is not good enough?

**Comment by leebenson** [comment]
Thanks for your time on this, @KROT47. I will test it out more thoroughly over the weekend/early next week, and give you the green light on a PR once I've had time to play around with it.

**Comment by KROT47** [comment]
Ok. Have a nice weekend ;)

**Comment by KROT47** [comment]
@leebenson so, is it no good?

**Comment by leebenson** [comment]
@KROT47 - my apologies, I've not had time to explore this in the detail it deserves yet. Will get back to you soon - thanks again!

**Comment by leebenson** [comment]
@jtmthf - do you have any thoughts on @KROT47's [implementation of Flow](https://github.com/KROT47/kit/tree/flow) for the kit - to possibly run alongside your Typescript variant?

I don't personally tend to use type checking in JS, so you may have more intelligible thoughts on the differences between Flow and TS, and if/how they might co-exist.

**Comment by tzarger** [comment]
Since the Typescript kit is falling behind and not an option at this point, thought about supporting this Flow kit or adding it in, since it can be added and enabled optionally if a person chooses to do so like in react-create-app? @leebenson

**Comment by leebenson** [comment]
@tzarger, it's definitely on my to-do to explore. Before I commit to a first-class Flow implementation, I need to set some time aside to go through @KROT47's code. I don't use Flow personally so I want to make sure it's not going to introduce maintenance overhead that I can't support.

As with the Typescript variant, it's easy to fall behind when there are multiple kits floating around, so I'd like to do something in core rather than branching off into different versions. I'm not sure whether Typescript or Flow should be the tool of choice for that support, though, or none of them - create-react-app offers instructions for [adding flow](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow) which would likely be relevant to any app, not just their starter kit specifically.

**Comment by leebenson** [comment]
I've decided to leave ReactQL as a 'pure' ES6 starter kit in the main. The Typescript branch has proven how easy it is to fall behind, and opting for Flow/TS as the main project is making an opinionated decision that risks dividing users.

I'll close this for now.
