### ISSUE TITLE
How do I handle server-side graphql errors?

### ISSUE THREAD

**Issue by NiluK** [reactql/kit#40]
Hi all, 

Firstly, I love the kit. It's been amazing. 

I've run into a small issue where I am using Authentication / Authorization for a GraphQL server. All it does currently is throw an error when the user is not Authenticated - this works fine client side, but on server side, it just fails entirely.

```
if (ctx.header.authorization) {
      token = verify(ctx.header.authorization.replace('Bearer ', ''), process.env.APP_SECRET);
    }
    if (!token) {
      return ctx.throw(401, '401 - Unauthorized');
    }
```

How would I tell the kit to ignore any GraphQL errors and still render the the React components? All I basically want it to do is still render even if there is an error. 

I've implemented this in the networkInterface, but it seems that the error still gets triggered in the kit.

```
const logErrors = {
  applyAfterware({ response }, next) {
    if (!response.ok) {
      response.clone().text().then(bodyText => {
        console.log(`Network Error: ${response.status} (${response.statusText}) - ${bodyText}`);
        next();
      });
    } else {
      response.clone().json().then(({ errors }) => {
        if (errors) {
          console.log('GraphQL Errors:', errors.map(e => e.message));
        }
        next();
      });
    }
  },
};

networkInterface.useAfter([logErrors]);
```

Thanks.

**Comment by leebenson** [comment]
By default, the server is set-up to catch errors in the generic handler that's set-up on all Koa routes:

```js
  .use(async (ctx, next) => {
    try {
      await next();
    } catch (e) {
      // TODO we've used rudimentary console logging here.  In your own
      // app, I'd recommend you implement third-party logging so you can
      // capture errors properly
      console.log('Error', e.message);
      ctx.body = 'There was an error. Please try again later.';
    }
```

That's because how errors should be handled is entirely up to the developer. In some cases, getting back an empty or erroneous response from a GraphQL endpoint is enough to crash the request rather than render back a half-formed component. Other times, you might not want to expose errors at all, or you may wish to implement your own third-party logging.

If you want to ignore errors, just wrap [this line](https://github.com/reactql/kit/blob/master/kit/entry/server.js#L123) in `try/catch` block, like:

```js
    try {
      await getDataFromTree(components);
    } catch (e) { /* ignore */ }
```

If you want the client and server Apollo clients to act differently in each environment, then [these lines](https://github.com/reactql/kit/blob/master/kit/lib/apollo.js#L28-L38) are what you'll want to edit.

By default, a client is created in the same way in each environment (with the exception of `ssrMode: true` on the server), but you could just as easily have a custom network interface on the client that handles 401 errors, and one on the server that ignores them entirely.

Hopefully that answers your Q, but if you need any further help lemme know.

**Comment by NiluK** [comment]
That fixed it, thank you very much.
