### ISSUE TITLE
Integrating third-party style frameworks modularly

### ISSUE THREAD

**Issue by clodal** [reactql/kit#50]
Would it be possible to extend ReactQL to allow for modular style imports from 3rd party frameworks? e.g. [Use modularized antd](https://ant.design/docs/react/introduce#Use-modularized-antd)

I read the ReactQL [docs](https://reactql.org/docs/stylesheets/globals) on third party frameworks. I understand that the current solution is to import the framework from the css side of things with the `@import` declaration in a `.global.(css|sass|scss|less)` file.

Would it possible for webpack css loaders to handle this differently via JS imports instead?

**Update**: Furthest i got was adjusting `webpack/common.js`'s `getModuleRegExp` method to set `modules: false` on a regex pointing to `node_modules/antd` path. Was able to load the antd framework styles without relying on `styles.global`. However, some styles required/imported by the antd framework were missing from this solution. I could see the styles but the framework's css animations were not working. Wound up falling back on the documented `styles.globals` method for now.

**Comment by leebenson** [comment]
Yes, it's possible. In the case of antd, you'd just need to update the Webpack babel config to use the antd babel plugin.

See this [block of code in webpack/browser.js](https://github.com/reactql/kit/blob/master/kit/webpack/browser.js#L51-L80) and [this in webpack/server.js](https://github.com/reactql/kit/blob/master/kit/webpack/server.js#L76-L93)

We don't support it in core because the number of possible frameworks and unique configuration settings would give rise to conflicts. But it's a trivial to add/change anything, usually just by changing the babel config of the above two files per https://ant.design/docs/react/introduce#Use-modularized-antd

**Comment by leebenson** [comment]
FWIW, I'd still recommend the `styles.global.css` import route generally. That way, you're guaranteed to import _everything_ in the framework's CSS, including (as you've seen) edge cases like animations -- and you don't have a separate plugin to maintain.
