### ISSUE TITLE
Integrating Kea.js

### ISSUE THREAD

**Issue by wmhafiz** [reactql/kit#54]
Hi, 

[Kea](https://kea.js.org/) is a very interesting library that provides high level abstraction between React, Redux, Reselect & Redux Saga & make coding in redux so much simpler & fun!

I'm trying to Integrate Kea.js library into ReactQL  and seems like I got both server & browser to render fine during `yarn start`, but `yarn build` fails with the following errors:

```
yarn build v0.22.0
$ cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors
ReactQL browser bundle in production mode building [=======             ] 35% (5.4 seconds)(node:61641) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Build completed in 5.906s

Build completed in 12.53s

Child
    Hash: f2c7f33e4aacc5f00c2d
    Time: 12536ms

    ERROR in vendor.283918ccad5a8334b903.js from UglifyJs
    Invalid assignment [vendor.283918ccad5a8334b903.js:1019,46]
Child
       46 modules

Couldn't parse bundle asset "/Users/hafiz/Development/git/test/reactql-kea/dist/public/browser.da1541e351531bdbce14.js".
Analyzer will use module sizes from stats file.

Webpack Bundle Analyzer saved report to /Users/hafiz/Development/git/test/reactql-kea/dist/report.html
error Command failed with exit code 2.
```

Please review the coding changes that I did as follows: [reactql-kea](https://github.com/wmhafiz/reactql-kea/commits/master)

I [added regenerator-runtime to entry/server.js](https://github.com/wmhafiz/reactql-kea/commit/793a0ddd101f5307bfd73b9f0bacfb342cd1ac08) because [Kea js requires it](https://github.com/keajs/kea/issues/16) & server side rendering would fail to start otherwise. (browser entry seems to have it already) 

Any ideas?

**Comment by leebenson** [comment]
I haven't explored Kea, so I don't have any immediate answers on that front - but I'm releasing kit v2.0 this weekend, which will refactor how reducers are added to the kit, so this might change how you go about connecting the two.

In ReactQL (as in classic Redux), actions are intended to be shared across multiple components and simply listen to state. Actions and reducers are defined once, not per-component like Kea seems to have. This might make dehydrating server state quite difficult.

I'm not sure if the two will be compatible, TBH.

Use Node > 7.6, and you shouldn't need regenerator-runtime on the server, BTW. This kit is designed for Node 7.6+

**Comment by mariusandra** [comment]
Hey, author of Kea here. Just to clarify some points about sharing actions between components.

The syntax of Kea that you might see on the [hompeage](https://kea.js.org) where actions are defined above components is just one of the ways to use the library. This way is analogous to using React's `setState`, but in a *reduxy* way.

Once you need to share logic between files, you take the same `@kea({})` call that you put above your components, replace `@kea({})` with `export default kea({})` and then you may import and use these actions from any component or logic. There is [a guide about connected components](https://kea.js.org/guide/connected) that goes in depth on this.

So to use the words of @leebenson , in Kea actions are intended to be shared across multiple components and components simply listen to state or fire actions. Actions and reducers are defined once and if they are only used by one component, you may inline them with the component itself.

I use kea in a [rather big webapp](https://www.apprentus.com/) that's also server rendered and everything about it (hydration, etc) works just fine.

Just wanted to clarify that point :).

...

As for the issue @wmhafiz has, I believe it's due to the fact that you're using webpack 3, which supports the `module` syntax. Kea exports its original untranspiled source via the [`module`](https://github.com/keajs/kea/blob/8e265d3fd550330ff57307bef17986ae68efc558/package.json#L8) keyword, but since in your `webpack/browser.js` the `node_modules` folder is excluded from being transpiled, the original ES6 source gets passed on to the browser. Uglifyjs doesn't know what to do with it and gives an error.

The solution is to either remove [the line](https://github.com/wmhafiz/reactql-kea/blob/86387a9f4bcdce90c7952d3b71f99c8b9ac757d8/kit/webpack/browser.js#L50) to exclude node_modules or to replace it with something like `exclude: /node_modules(?!\/kea)/`

**Comment by leebenson** [comment]
Thanks for taking the time to clarify, @mariusandra.

**Comment by wmhafiz** [comment]
Great answer @mariusandra !
And indeed that solved the build problem! 
Cheers!

Since @leebenson is releasing kit 2.0 soon, I'll monitor the situation with great interest.
