### ISSUE TITLE
External graphql server

### ISSUE THREAD

**Issue by jimmyjamieson** [reactql/kit#90]
I'm not sure if this is me, or just the docs being slightly out of date.

However, in config/project.js I've added a graph.cool endpoint to test i.e.

import config from 'kit/config';
config.enableGraphQLServer(true);
config.setGraphQLEndpoint('https://api.graph.cool/simple/v1/xxx');

But I'm not sure how I'm supposed to test if this actually works? From what I understand I can just create a new query in src/graphql/queries and call that. Or http://localhost:8081/graphql should point to the external server, not the local.

Maybe I'm missing something?

**Comment by noeljackson** [comment]
@jimmyjamieson This is a confusing one. But it makes sense.

I'm not a fan of having GraphQL servers and clients wrapped together, but ReactQL has moved in that direction, so you need to DISABLE the internal server, for the external endpoint to work.

```
config.graphQLServer = false;
```
or

```
config.enableGraphQLServer(false);
```

Depending on the version of ReactQL you're using.

**Comment by jimmyjamieson** [comment]
@noeljackson thanks. Doesn't seem to make a shred of difference. http://localhost:8081/graphql is still showing local with the dummy message block.

Perhaps I need to set these config options in another place? The docs do say config/project.js though

**Comment by jimmyjamieson** [comment]
Im on the latest kit provided by the cli

**Comment by noeljackson** [comment]
@jimmyjamieson Try setting it in app.js: https://github.com/reactql/kit/blob/master/src/app.js Read through the comments, and apply the logic of "disabled GraphQL server" == "I can use an external endpoint"

**Comment by leebenson** [comment]
`config.enableGraphQLServer()` is for enabling the built-in GraphQL server. _Every_ ReactQL project assumes that GraphQL will be used _somewhere_ (either built-in, or externally), so there's no equivalent for disabling GraphQL entirely-- the aforementioned function simply enables the built-in server.

If you want to point to an external server, use:

```js
config.setGraphQLEndpoint('https://external.server'); // <-- full GraphQL URI
```

... _without_ any calls to 'enableGraphQLServer()'. The source code for `setGraphQLEndpoint()` is [here](https://github.com/reactql/kit/blob/master/kit/config.js#L48-L52).

I'd always recommend reading the source comments, since that'll give you the most up-to-date documentation. The docs at https://reactql.org/docs are a few versions behind (bringing them up to date is a pretty significant undertaking that, sadly, I've not had the time to do lately.) Things changed pretty quickly between v1 and v2 of the kit, and I'm still catching up.

Try the above and see how you get on. Any further Qs, just let me know.

**Comment by jimmyjamieson** [comment]
Ok got it. Just in case anyone else has the same issue

open src/app.js

change line config.enableGraphQLServer();
to
// config.enableGraphQLServer();
config.setGraphQLEndpoint('https://api.graph.cool/simple/v1/xxxx');

Thanks :)

**Comment by webberwang** [comment]
@jimmyjamieson Inside the if (SERVER) block right?

**Comment by webberwang** [comment]
@jimmyjamieson I believe you still need the line `enableGraphQLServer`. It wasn't working without that line for me when I'm using an external GraphQL service like GraphCMS
