### ISSUE TITLE
Unable to run app with PM2 for production

### ISSUE THREAD

**Issue by Ahakke** [reactql/kit#96]
Hello,

i want to deploy my reactql app using the processmanager pm2 (v 2.7.1)

All attempts to launch the app using pm2s "npm start" scripts are failing.

i have tried two different commands:

pm2 start npm -- start  //works with non reactql apps

using the pm2 ecosystem file:
apps:[{
name:"myapp",
script:"npm",
args:"start",
}]

All my other node apps work fine except or this one..

my app uses reactql 2.3
Migrating to a higher version is not possible..
Which parts do you recommend to fix?
Thank you

**Comment by klarstrup** [comment]
after `npm run build` the command to start a production server is `npm run server`

**Comment by leebenson** [comment]
I'll tackle this in the next release. PM2 would be a nice addition.

**Comment by leebenson** [comment]
I've added PM2 to the project's [Dockerfile](https://github.com/reactql/kit/blob/master/Dockerfile) in [2.9.4](https://github.com/reactql/kit/releases/tag/2.9.4), which is also fired automatically when spawning a production build with Docker Compose:

```
docker-compose up
```

By default, the Dockerfile will exec in cluster mode and spawn one process per CPU core, which makes it ideal for production.

In the development config, it just spawns `npm start` by default, to enable hot code reloading:

```
docker-compose -f docker-compose.dev.yml up
```

If you don't want to use Docker and you're simply using pm2 locally, then you'd need to create a script that could effectively emulate the `npm start` command defined [in package.json](https://github.com/reactql/kit/blob/master/package.json#L19), since it doesn't appear that PM2 can natively run NPM script commands.
